### ISSUE TITLE
Keyboards

### ISSUE THREAD

**Issue by widg** [black-river/laravel-telegram-bot#1]
One of the coolest things about Telegram Bot API are the new custom keyboards. Is it possible to add it?

**Comment by seleznevdev** [comment]
@widg, Sure. Using the client you're free to use any of the available [methods](https://core.telegram.org/bots/api#available-methods) and [types](https://core.telegram.org/bots/api#available-types).

``` php
$keyboardMarkup = [
    'keyboard' => [
        [['text' => '🍕 Pizza'], ['text' => '🍔 Hamburger'], ['text' => '🌭 Hot Dog']],
        [['text' => '🍗 Poultry Leg'], ['text' => '🍖 Meat on Bone'], ['text' => '🍳 Egg']],
    ]
];

$this->client->send('sendMessage', [
    'chat_id' => $this->request->json('message.chat.id'),
    'text' => 'Choose your food...',
    'reply_markup' => json_encode($keyboardMarkup),
]);
```

![food-command](https://cloud.githubusercontent.com/assets/5261079/18988762/29da1a68-8719-11e6-93c8-d58f89413337.png)
